
:linkcss:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: stylesheets/
:stylesheet:  colony.css
:data-uri:
:toc:


== Poetry
(By Dr.Lakshmana Rao Ayyagari)

=== అల  -   అక్షరాలు

పద్యం కాదు ! +
గద్యం కాదు !!
కవిత కాదు ! +
కవిత్వమసలే కాదు !! +
వేదమె నిత్యం +
అధీతమైతే +
అలలా నాలో +
వెలిగిన భావం +
అక్షర రూపం +
దాల్చిన సమయం +
కలమును కూడిన +
ప్రక్రియ కావున +
అల యని పలుకుట +
సమమని తోచెను +
వినయము కూడి +
పలికెద నేను +
తలచిన వారికి +
కలుగును తప్పక +
భగవద్గీతే +
శాంతిని  ఇచ్చే +
సత్యమనే +
శ్రధా భావం ! +

=== వేదాంత ఘోష  (దుఃఖ సం యోగ వియోగం యోగ సఞ్గితం)

నువ్వు నువ్వు కాదని  +
నీకు నువ్వు తెలియడం  +
వేద జ్ఞాన ప్రతి ఫలం +
అన్యధా అసంభవం +

తెలిసిన మరు క్షణం +
కలిగే ప్రతి లాభం +
ముక్తి మార్గ సూచికం +
సంగ దోష నాశకం +

తదుపరి నీ వ్యవహారం +
సాగును నిరంతరం +
దుఃఖ జ్వాల దగ్ధ వృత్తి  +
దగ్గరకే రాకుండా +
దరిదాపుకి దూరంగా +

మృష జాలం  +
కృషి భేద్యం +
ఋషి వాక్యం +
సహకరణం +




===  కృపణాః ఫల-హేతవః
ఉత్తిష్ఠ  నరశార్దూల ! తత్విద్ధి పరిప్రశ్నేన !!

నువ్వు నేనూ +
ఉన్నామా ? +
ఉన్నామని +
అనుకున్నామా ! +
ఉన్నది అన్నది +
ఏమై ఉండును +
అన్నదాని కై +
అర్ధం వెతుకు +
వ్యర్ధం చేయకు +
ఇచ్చిన బుధ్ధినివేదం +



సృష్టి రహస్యం +
చూసిన ద్రష్టల +
యోగ నిష్టయే +
అధిష్టానమై +
ఓం కారమై +
ప్రణవ నాద మై +
ధరణిని నిండిన +
ధ్వని తరంగమే +
వేద స్వరూపం +
శబ్ద ప్రమాణం +





=== మహా మోహలతా నిబద్ధపదము





నేనూ నాదను +
అహమే ఇహలో +
మోహాజాలం +
మీలో నాలో +
మారడమంటే +
యేదో కాదు +
గారడి నుంచీ +
వేరగుటేను +
మరిన నాడే +
తీరును దుఃఖం +
మరిన వాడే +
చేరును గమ్యం +


ఊహ గలంగి జీవనపుటోలమునం బడి పోరుచున్ మహా +
మోహలతా నిబద్ధపదమున్ విడిపించుకొనంగ లేక సం +
దేహముఁ బొందు దేహి క్రియ దీనదశన్ గజ ముండె భీషణ +
గ్రాహ దురంత దంత పరిఘట్టిత పాదఖురాగ్ర శల్యమై.

=== What you think what you are is not what you are


నాలో ఉన్నది నేను కానిదీ +
నాతో ఆటను ఆడిస్తున్నది +

నాలో ఉన్నది నేను కానిదీ +
నాలో దూరి తానే నేనై +
నాతో ఆటను ఆడిస్తున్నది +

మాటా మనసూ చేష్టా చింతా +
అంతా తానై అంతా తనకై +
నాలో ఉన్నది నేను కానిదీ +
నాతో ఆటను ఆడిస్తున్నది +

నష్టం తెచ్చే ఇష్టం ఐనా +
ఇష్టం వెనుకే పరుగె ట్టిస్తూ +
తీరని ఇష్టం కలిగే కష్టం +
జన్మకి కర్మ కి కారణ మౌతూ +
సంసార మనే ఈ సాగరంలో +
నా తో ఈతను ఈదిస్తున్నది +
నాతో ఆటను ఆడిస్తున్నది +

ఆది లేనిదీ అనంత మైనదీ +
సత్య మైనదీ చిదానంద మైనదీ +

నైజము నాదని +
నిజముని దాచే +
మహా మోహమనే +
ముసుగుని కప్పి +
ఆశా పాశం కళ్ళెం వేసి +
నాలో దూరి స్వారీ చేస్తూ +
నాతో పరుగును పెట్టిస్తు న్నది +

మళ్ళీ మళ్ళీ జన్మను ఇస్తూ +
నాలో ఉన్నది నేను కానిదీ +
నాతో ఆటను ఆడిస్తున్నది +



=== తమసోమా జ్యోతిర్గమయా




చదివిన కొద్దీ చదవనిదెంతో +
ఉండే ఉండక ఉండకపోదు +

చూసిన కొద్దీ చూడనిదెంతో +
ఉండే ఉండక ఉండకపోదు +

వచ్చిన కొలదీ రానిది యెంతో +
ఉండే ఉండక ఉండకపోదు +

ఎదిగిన కొలదీ ఎదగని చోటూ +
ఉండే ఉండక ఉండకపోదు +

ఎక్కిన కొలదీ ఎక్కని శిఖరం +
ఉండే ఉండక ఉండకపోదు +

అంతు లేనిది ఆశాపాశం +
అలలా లేచే సంకల్పాలు +
ఆగవు ఎప్పుడూ ఆఖరి దాకా +
వాటితొ మనసు తీసే పఱుగూ +
వెలుగుని చూసీ ఆపకపోతే +
అసంతృప్తి ఏ ఆఖమజిలీ +


inspired by +

యస్య సర్వే సమారమ్భాః కామసఙ్కల్పవర్జితాః. జ్ఞానాగ్నిదగ్ధకర్మాణం తమాహుః పణ్డితం బుధాః৷৷4.19৷৷


=== అధో గతి ని ఏమరించి పురో గతి ని సాధిస్తున్నాం +

మానవాళి అధో గతికి +
మరో అడుగు ముందు కేస్తు +
పురో గతి ని సాధించాం +
పురాలెన్నో నిర్మించాం +
సౌధా ల తొ నింపేశాం +
సౌభాగ్యం ప్రకటించాం +
సాంకే తిక విజ్ఞానం +
చివరిటంచు వీధుల్లో +
ప్రగతి పధం సృ ష్టించాం +
అధో గతి ని గుర్తించక +

కనిపెట్టిన పరికరాలు +
సమకూర్చిన దేమంటే +
అణచి ఉంచిన +
ఆలోచనలకు +
అవధి తెగిన అవకాశం +
తప్పు దారి తొక్కెందుకు +

మాదంటూ మతమంటూ +
మా దేముడు గొప్పంటూ +
వెళ్ళిన ప్రతి చోటా +
గుళ్ళ మీద గుళ్ళు కట్తి +
దేవుళ్ళని స్థాపిం చాం +
మా గొప్పకి చిహ్నంగా +
జనార్ధనుని సేవంటూ +
ధనార్జనే ముఖ్యంగా +
భగవంతుని మాటేంటో +
అసలైనా వినకుండా +

నరలోకం నడక తీరు +
వెనకడడుగు గమనం తో +
మానవాళి అధో గతికి +
మరో అడుగు ముందు కేస్తు +
పురో గతి ని సాధిస్తున్నాం +
అధో గతి ని ఏమరించి

=== జగత ఈశధీ యుక్త సేవనం


తడ బడు అడుగుల బుడతడి కైనా +
వడి వడి పరుగుల గడ సరి కైనా +
అడు గిడు సందడి కది ఆధారం +
అడుగును కిందకి ఈడ్వడమై (gravity) +
పుడమిని ఇమిడిన ఈశ్వరుడే +

గుడి లో గడపకి అవతల ఉన్నది +
వాడే దేముడు అనుకుంటూ +

మడి తో చేసే  పూజ కి మెచ్చి +
అడిగిన వన్నీ ఇచ్చే వాడని +

నమ్మే మూర్ఖుడి  గడ బిడ తీర్చుట +
ఈశుడి కైనా  గడవని పనిలే ! +


=== బ్రహ్మ యోగం

బ్రహ్మ యోగ యుక్తాత్మ +

బాహ్యస్పర్శేష్వసక్తాత్మా విన్దత్యాత్మని యత్సుఖమ్ । +
స బ్రహ్మయోగయుక్తాత్మా సుఖమక్షయమశ్నుతే ॥౫.౨౧॥ ||5.21|| +
భగవాన్ ఉవాచ -  భగవద్ గీత +


తెలుసు తెలుసనే తెలివి తక్కువ +
తెలియవలసిన తెలివినంతా +
తొక్కి పట్టీ  పక్క నెట్టీ +
రెక్క లొ చ్చిన నాటి నుంచీ +
పక్క వాడిని  మించి పోయే +
యెక్కువే  నా మక్కువంటూ +
మొక్కు లెన్నో  మొక్కు కుంటూ +
చక్క నైనా  జీవితాన్ని +
దుః ఖధామం  చేసు కుంటూ +
చచ్చి పుట్టే  మనిషి కోసం +

మాధవా +
నీ నోటి నుంచీ +
మాకు అందిన  మంచి మాట +
యోగ శాస్త్రం  దీని పేరు +
యోగ్య తమము  వేరు లేదుకెరటం కోరిక ఏమై యుండును +


విరగని పరుగుతో +
ఉరకలు తీస్తూ +
నురగల ఉరవడి చూపించాలని +

సాగర తీరం జరిగేదేమిటి +

విరిగే పరుగు +
ఉండని నురగ +
వెనుకే ఇంకొక వేరొక కెరటం +

=== శరీర యాత్ర


ఇంపు ఇంపని +
యెంపి యెంపి +
సౌంపులెన్నో +
చేరదీసా +

పెంపు పెంపని +
పరుగుతీసి +
వంపు వంపున +
అలసిపోయా +

వింత వింతగ +
చెంత చేరిన +
చింతలన్నీ +
చంపలేక +

చంప బోయే +
చావు చెంతకు +
కొంత కొంతగ +
చేరువయ్యా +

చింత లన్నియు అంతమయ్యెను +
వేదాంతము స్వంత మైనను. +

Inspired by +

బాలస్తావత్క్రీడాసక్తః +
తరుణస్తావత్తరుణీసక్తః । +
వృద్ధస్తావచ్చిన్తాసక్తః +
పరమే బ్రహ్మణి కోఽపి న సక్తః ॥౭॥


=== నిక్క మైన మంచి నీల మొక్కటి చాలు



అలనాడు ఆసువుగ +
ఇల రాజు అడిగేను +
అలసాని పెద్దన్న +
అలవోకగా నుడివె +
గుండెలో ఉబికెను +
నిండైన రసభూతి +
మండలాధిపతి వేసె +
పండితులు హర్షించ +
పాండితీ వరునికి +
గండ పెండేరము +

ఆరీతి వర్ణించ ఆ కైత చాతురి +
యే రాత వారికీ  చేత కాబోదు +
ఈరీతి వివరింతు నేనెంచు అర్హతలు +
సరైన కవితకి వినయతతొ నేను +

పదాలు అందమై +
పాదరస చందమై +
పెదవి పై తేలుతూ +
పదనిసలు పా డాలి +

గల గలా చదివితే +
కిల కిలా రావ మై +
కిత కితలు కలిగించి +
వెతలు మరిపించి +
మతిని మురిపించాలి +

తెలుసుకోవాలనే +
తెలివి గల వారికి +
విలువలని తెలిపే +
విలువగల రాతగా +

భావార్ధ గంభీర +
కుంభమై వర్ధిల్లు +
శబ్ద సుందరమైన +
లబ్ధి గల రాతగా +

కల కాల ముండాలి +
ఇల లోన నిండాలి +

=== ప్రకృతేః క్రియమాణాని గుణైః కర్మాణి సర్వశః. అహఙ్కారవిమూఢాత్మా కర్తాహమితి మన్యతే৷৷3.27৷৷


light in the room +
from a flickering flame +
wick and the wax +
claiming the fame +
known not the name +
Of the REAL and all around +
Causing this game +
from timeless time +

=== ఊహించు -    ఆలోచించకు




ఆలోచన అవరోధాలకి నాంది +
ఊహ పురోగమనానికి పునాది +

ధరాతలం బీటలలో, +
వ్యధా బ్రతుకు వాడొకడు +
ధరాధిపతి కావొచ్చు, +
రధాల  పై తిరగొచ్చు +

ఊహించే విధానమే! +
బలానికీ ప్రధానం!! +

ఆధారమె  కరువంటూ, +
విధారతతొ వేరొకడు +
విధాత చేయు  రాతంటూ, +
వ్రుధా చేయు బ్రతుకంతా +

ఉహించే విధానమే! +
పతనానికీ, సమాధానం!! +

ఉదకం లో మందు కన్న +
ఊహ యిచ్చు హాయి మిన్న +
అందరాని పొందుకన్న +
ఊహ యిచ్చు విందు మిన్న +

ఊహించే విధానమే +
ఊరించీ గెలిపించినా ! +
ఊహించే విధానమే +
ఉరేసి చంపించినా !! +


===  ఊహల ఉయ్యాల   ఆకులు చెప్పేదేమిటీ ?
మాకూ మీకూ ఒకటే చీకటి !! +




ఆ రోజు +
ఆ వీ ధి మలుపులో, +
ఆ కొమ్మ చివరలో +
ఆకులన్నీ కలసి పలకరించెను నన్ను ! +

వాలి వున్న రెమ్మలకీ, వాలలేని కొమ్మలకీ +
జాలి తో తోబుట్టువులమై , నేల తలకి మానికమై +
గాలి ఉనికికి మూలమై, మూల మూలా విస్తరించి +
రాలి పోక,  రోజు రోజు మోజు తీర్చే వారమంటూ. +

ఈ రోజూ +
ఆ వీ ధి మలుపులో, +
ఆ కొమ్మ చివరలో +
ఆ ఆకులే కలసి వెక్కిరించెను నన్ను !! +

పచ్చ దన మొచ్చెనని ముచ్చటతొ మురిసి పోయి +
వచ్చిన యెర్ర రంగు చూసి వెర్రిగా  వూగి పోయి +
హెచ్చిన రంగు తెచ్చిన,  హంగుతో  మారి పోయి +
వొచ్చే కాలం,  తెచ్చే మార్పు  తెలుసుకోలేకపోయి. +

ఆకు వే అయిన గానీ +
గాక రాకుమారి వైన నేమి +
పలకరించి పొగరు చూపకు +
పరిహసించి వెక్కిరించకు ! +

కల కాల ముండదీ, మిల మిలల హొయలు +
బలమైన గాలొచ్చి. గిల గిలా రాలించి +
ఇల మీద  చెత్తలో, కలపి వేసే  రోజు +
మెల మెలా రానుంది, బలమైన నిజమిది !!+

=== గీతామృతపానవిశేషమత్తచిత్తమేరీతి ఇతరముల చేర నేర్తు


ధ్రుడమది +
ధృవమది +
ధృతి యది +
భ్రమతకు లొంగని +
ధృతి యది +

మతి అది +
గతి అది +
రతి యది +
brahmaను చేరిన +
రతి యది +

పదమది +
పరమది +
వరమది +
నరులకు అంతిమ +
బలమది +


=== యదా తే బుద్ధిః మోహ-కలిలం వ్యతితరిష్యతి


రాత్రైన పగలైన +
ఒక్కడే సూర్యుడు +
అక్కడే ఉంటాడు ! +

కర్తవ్య వర్తి ఐ +
భూమియూ తానై +
గిర గిర తిరుగుతూ +
తిరుగుతూ తిప్పుతూ +
మన కళ్ళు కప్పుతూ +
చీకటిని వెలుతురిని +
ప్రతి రోజు కలిగించు +
క్రమమైన పద్ధతే +
విష్ణువూ జిష్ణువూ !! +

అదిలేక మనకి +
బ్రతుకన్నదే లేదు ! +

గుడి కట్టి మూర్తొకటి +
గుర్తుగా పెట్టి +
మడికట్టి పూజొకటి +
జరిపించి మురింపిచి +
దేముడా నాగోల +
వినవయ్య నువ్వు +
అది ఇవ్వు ఇది కాదు +
ఇది ఇవ్వు అది కాదు +
అనుకొంటు మసలేటి +
మానిషిలో మాయ +
తీరేది కాదు, మారేదిలేదు +
దుఃఖ మన్నది మనలో +
పోయేది లేదు ! +
గీతాలో బుధ్ధి +
బుధ్ధికెక్కిననాడు +
వద్దు వద్దన్నా +
స్వర్గమే నీ బ్రతుకు !! +

=== పశ్యన్ ఆత్మని మాయయా !!




సురీడు ఎప్పుడూ +
అక్కడే ఉంటాడు ! +

తెలవారు జామున +
తూర్పులో ఉన్నోడు +
కాసేపు చూస్తే +
పడమరికి పోతాడు +
అనుకోనివాడు +
ఉండడే ఉండడు +
వివేకవంతుడు +
వివరించి చెప్పినా +
అనుభూతి మాత్రం +
అదే ఒక విధం +
బ్రతుకంత మనకి +
బ్రతికున్ననాళ్ళు +

ప్రపంచమంతా +
చుసేది చేసేది +
బయటనే ఉంటుంది +
అనుకునేవాడికీ +
నిద్ర లేపేది ఐ ఉన్నదే +
ఉపనిషద్ వాక్యాల +
వివేక ధోరణి +


=== యుధ్యస్వ విగత-జ్వరః  యోగః కర్మసు కౌశలమ్

యోగాయ యుజ్యస్వ +



సాగించకు సాగించకు +
సాగించకు  సంసారం +
సాగర పైనంలో సాగని వైనంగా +
వీగే గాలికి ఊగే నావలా +
గమ్య రహిత విహంగంగా +
స్పంద విహిత మ్రుదంగగా +
దీనంగా దైనందిన రోదంగా +
సాగించకు సంసారం +
భారంగా నిస్సారంగా +

సంసారం మన జీవన విధానం +
రస రసాల సుమరస రసాయనం +
అవసరాలకి సరసమైన విరామం +
విరస సరస విన్యాసపు కాసారం +
సతీ పతుల, సుతుల హితుల +
కలిత లలిత అతులిత లతా వలయం +

మరైతే కర్మసన్యాసం ఎందుకు +
కర్మసన్యాసం అంటే +
కర్మని వదిలిపెట్టడం కాదురా +
వెర్రి పప్పా +

